### ISSUE TITLE
ValueError: Missing staticfiles manifest entry for 'dist/jsoneditor.9.7.4.min.css'

### ISSUE THREAD

**Issue by sowinski** [cursive-works/wagtail-json-widget#10]
Hi,

in my production environment I got this error.

```
     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'dist/jsoneditor.9.7.4.min.css'
```

I guess the way how we import the static files is wrong while using static paths instead of static()

**Comment by waldo90** [comment]
Hi sowinski,

I've merged your PR and released / tagged version 0.0.6 to include it. I'm expecting that your fix will also resolve this issue. Many thanks!
