### ISSUE TITLE
BUG: Editor-options are not taking into consideration

### ISSUE THREAD

**Issue by fmfeit** [cursive-works/wagtail-json-widget#12]
Hello,

thank you for providing this widget.

It seems like the options-dict passed to the constructor of JSONEditorWidget are not passed on to the JavaScript file. Instead the editor-options are hardcoded in line 10 of `json_widget.js`.

Best regards

**Comment by waldo90** [comment]
Hi @fmfeit , I'll take a look at improving this when I get a chance. Unfortunately I can't give you a timeline as I'm busy with other projects right now. That said, if you can make the change and submit a Pull Request I'll happily review and merge as appropriate.

Thanks for your feedback!

**Comment by waldo90** [comment]
fixed in 8a9a66ac383386ec145717428e935662d061bace

**Comment by waldo90** [comment]
Released 0.0.8
