### ISSUE TITLE
TemplateDoesNotExist: wagtail_json_widget.html

### ISSUE THREAD

**Issue by sowinski** [cursive-works/wagtail-json-widget#7]
Hi,

I can not run your example. I got the error:

```
TemplateDoesNotExist at /cms/pages/372/edit/
wagtail_json_widget.html
Request Method:	GET
Request URL:	http://10.8.0.1:8000/cms/pages/372/edit/
Django Version:	3.2.14
Exception Type:	TemplateDoesNotExist
Exception Value:	
wagtail_json_widget.html
Exception Location:	/home/devmzguru/git/myvenv/lib/python3.7/site-packages/django/template/backends/django.py, line 84, in reraise
Python Executable:	/home/devmzguru/git/myvenv/bin/python3
Python Version:	3.7.3
```

Using Django 3.2 and Wagtail 2.13.5

Which version do you use?

**Comment by sowinski** [comment]
Your pypi package is broken. You need to include the templates folder.

Would be nice to see tests. (CI)

**Comment by sowinski** [comment]
`pip3 install git+https://github.com/cursive-works/wagtail-json-widget.git@88a54a26d9ca744c20af8a666ad07178ca8c5e8a`

Current branch is also not adding the template dirs. Why?

**Comment by sowinski** [comment]
https://github.com/cursive-works/wagtail-json-widget/pull/8

please add my pull request :)

**Comment by marts** [comment]
Hi @sowinski, just to let you know that the author of this package is currently on holiday. I'm sure they will consider your PR next week when they return, and be able to help you with the issues you are having.

**Comment by waldo90** [comment]
Hi @sowinski, I've merged your PR to fix this issue. Thank you. PyPI release to follow.
